foreground              #e3e2e9
background              #1e1f25
selection_foreground    #dde1f9
selection_background    #414659

cursor                  #b3c5ff
cursor_text_color       #1a2e60

url_color               #e2bbdc

active_border_color     #b3c5ff
inactive_border_color   #45464f
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #dbe1ff
active_tab_background   #324478
inactive_tab_foreground #c5c6d0
inactive_tab_background #1e1f25
tab_bar_background      #121318

mark1_foreground #1a2e60
mark1_background #b3c5ff
mark2_foreground #2a3042
mark2_background #c1c6dd
mark3_foreground #422741
mark3_background #e2bbdc

color0 #45464f
color8 #8f909a

color1 #ffb4ab
color9 #93000a

color2  #b3c5ff
color10 #dbe1ff

color3  #e2bbdc
color11 #ffd6f8

color4  #c1c6dd
color12 #dde1f9

color5  #324478
color13 #4a5c92

color6  #414659
color14 #5a3d58

color7  #c5c6d0
color15 #e3e2e9
